name: Go and Rust cross-platform testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Linux job
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TEST_TOKEN }}
          submodules: recursive

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build Rust library for Linux
        run: cargo build --manifest-path ./pkg/test-rust/lib/hello/Cargo.toml -r

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build and test Go code
        run: go run main.go

  # macOS job
  macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TEST_TOKEN }}
          submodules: recursive

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build Rust library for macOS
        run: cargo build --manifest-path ./pkg/test-rust/lib/hello/Cargo.toml -r

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build and test Go code
        run: go run main.go

  # Windows job
  windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TEST_TOKEN }}
          submodules: recursive

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build Rust library for Windows
        run: cargo build --manifest-path ./pkg/test-rust/lib/hello/Cargo.toml -r

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build and test Go code
        run: go run main.go
