name: Windows

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  # Windows job
  windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TEST_TOKEN }}
          submodules: recursive

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build Rust library for Windows
        run: cargo build --manifest-path ./pkg/test-rust/lib/hello/Cargo.toml -r

      - name: List directory contents for debugging
        run: |
          cd D:\a\test-golang\test-golang\pkg\test-rust\lib\hello\target\release
          dir

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Set CGO environment variables
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I$(pwd)/pkg/test-rust/lib" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L$(pwd)/pkg/test-rust/lib/hello/target/release -lhello" >> $GITHUB_ENV

      - name: Build and test Go code
        run: go run main.go
